TESTNET_TALGO_APP_ID = 724519988
MAINNET_TALGO_APP_ID = 2537013674

TESTNET_TALGO_STAKING_APP_ID = 724676904
MAINNET_TALGO_STAKING_APP_ID = 2537022861

TESTNET_TALGO_ASSET_ID = 724519992
MAINNET_TALGO_ASSET_ID = 2537013734

TESTNET_STALGO_ASSET_ID = 724676936
MAINNET_STALGO_ASSET_ID = 2537023208

# App Constants

APP_LOCAL_INTS = 3
APP_LOCAL_BYTES = 1
APP_GLOBAL_INTS = 16
APP_GLOBAL_BYTES = 16
EXTRA_PAGES = 3

VAULT_APP_ID_KEY = b"vault_app_id"
TINY_ASSET_ID_KEY = b"tiny_asset_id"
TALGO_ASSET_ID_KEY = b"talgo_asset_id"
STALGO_ASSET_ID_KEY = b"stalgo_asset_id"

TOTAL_REWARD_AMOUNT_SUM_KEY = b"total_reward_amount_sum"
TOTAL_CLAIMED_REWARD_AMOUNT_KEY = b"total_claimed_reward_amount"
CURRENT_REWARD_RATE_PER_TIME_KEY = b"current_reward_rate_per_time"
CURRENT_REWARD_RATE_PER_TIME_END_TIMESTAMP_KEY = b"current_reward_rate_per_time_end_timestamp"

TINY_POWER_THRESHOLD_KEY = b"tiny_power_threshold"
LAST_UPDATE_TIMESTAMP_KEY = b"last_update_timestamp"
ACCUMULATED_REWARDS_PER_UNIT = b"accumulated_rewards_per_unit"
TOTAL_STAKED_AMOUNT_KEY = b"total_staked_amount"
TOTAL_STAKER_COUNT_KEY = b"total_staker_count"

PROPOSED_MANAGER_KEY = b"proposed_manager"
MANAGER_KEY = b"manager"

MAX_UINT64 = 18446744073709551615
RATE_SCALER = 1_000_000_000_000
