HOUR = 60 * 60
DAY = 24 * HOUR
WEEK = 7 * DAY

BYTES_ZERO = b'\x00'
BYTES_ONE = b'\x01'

TESTNET_TINY_ASSET_ID = 258703304
MAINNET_TINY_ASSET_ID = 2200000000

TESTNET_VAULT_APP_ID = 480164661
MAINNET_VAULT_APP_ID = 2200606875

TESTNET_REWARDS_APP_ID = 336189106
MAINNET_REWARDS_APP_ID = 2200608153

TESTNET_STAKING_VOTING_APP_ID = 360907790
MAINNET_STAKING_VOTING_APP_ID = 2200609638

TESTNET_PROPOSAL_VOTING_APP_ID = 383416252
MAINNET_PROPOSAL_VOTING_APP_ID = 2200608887

TESTNET_ARBITRARY_EXECUTOR_APP_ID = 0       # Temporary
MAINNET_ARBITRARY_EXECUTOR_APP_ID = 0       # Temporary

TESTNET_FEE_MANAGEMENT_EXECUTOR_APP_ID = 0      # Temporary
MAINNET_FEE_MANAGEMENT_EXECUTOR_APP_ID = 0      # Temporary

TESTNET_TREASURY_MANAGEMENT_EXECUTOR_APP_ID = 0     # Temporary
MAINNET_TREASURY_MANAGEMENT_EXECUTOR_APP_ID = 0     # Temporary

TINY_ASSET_ID_KEY = b'tiny_asset_id'
VAULT_APP_ID_KEY = b'vault_app_id'

INCREASE_BUDGET_APP_ARGUMENT = b"increase_budget"
GET_BOX_APP_ARGUMENT = b"get_box"
SET_MANAGER_APP_ARGUMENT = b"set_manager"
SET_PROPOSAL_MANAGER_APP_ARGUMENT = b"set_proposal_manager"
SET_VOTING_DELAY_APP_ARGUMENT = b"set_voting_delay"
SET_VOTING_DURATION_APP_ARGUMENT = b"set_voting_duration"
