from tinyman.constants import MINIMUM_BALANCE_REQUIREMENT_PER_BOX, MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE

MAX_OPTION_COUNT = 16

# Global States
PROPOSAL_INDEX_COUNTER_KEY = b'proposal_index_counter'
VOTING_DELAY_KEY = b'voting_delay'
VOTING_DURATION_KEY = b'voting_duration'
MANAGER_KEY = b'manager'
PROPOSAL_MANAGER_KEY = b'proposal_manager'

# Box
PROPOSAL_BOX_PREFIX = b'p'
STAKING_VOTE_BOX_PREFIX = b'v'
STAKING_ATTENDANCE_BOX_PREFIX = b'a'

STAKING_PROPOSAL_BOX_SIZE = 49
STAKING_VOTE_BOX_SIZE = 8
STAKING_ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE = 24

STAKING_VOTING_APP_MINIMUM_BALANCE_REQUIREMENT = 100_000

STAKING_PROPOSAL_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (60 + STAKING_PROPOSAL_BOX_SIZE)
STAKING_VOTE_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (17 + STAKING_VOTE_BOX_SIZE)
STAKING_ATTENDANCE_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (41 + STAKING_ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE)

STAKING_PROPOSAL_CATEGORY = "farming-rewards-distribution"

CREATE_PROPOSAL_APP_ARGUMENT = b"create_proposal"
CANCEL_PROPOSAL_APP_ARGUMENT = b"cancel_proposal"
CAST_VOTE_APP_ARGUMENT = b"cast_vote"
