from tinyman.constants import MINIMUM_BALANCE_REQUIREMENT_PER_BOX, MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE

# Global States
PROPOSAL_INDEX_COUNTER_KEY = b'proposal_index_counter'
VOTING_DELAY_KEY = b'voting_delay'
VOTING_DURATION_KEY = b'voting_duration'
PROPOSAL_THRESHOLD_KEY = b'proposal_threshold'
PROPOSAL_THRESHOLD_NUMERATOR_KEY = b'proposal_threshold_numerator'
QUORUM_THRESHOLD_KEY = b'quorum_threshold'
MANAGER_KEY = b'manager'
PROPOSAL_MANAGER_KEY = b'proposal_manager'
APPROVAL_REQUIREMENT_KEY = b'approval_requirement'

# Box
PROPOSAL_BOX_PREFIX = b'p'
ATTENDANCE_SHEET_BOX_PREFIX = b'a'

PROPOSAL_BOX_SIZE = 116 + 34 + 32
ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE = 24

PROPOSAL_VOTING_APP_MINIMUM_BALANCE_REQUIREMENT = 100_000

PROPOSAL_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (60 + PROPOSAL_BOX_SIZE)
ATTENDANCE_SHEET_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (41 + ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE)

CREATE_PROPOSAL_APP_ARGUMENT = b"create_proposal"
CAST_VOTE_APP_ARGUMENT = b"cast_vote"
GET_PROPOSAL_APP_ARGUMENT = b"get_proposal"
GET_PROPOSAL_STATE_APP_ARGUMENT = b"get_proposal_state"
HAS_VOTED_APP_ARGUMENT = b"has_voted"
APPROVE_PROPOSAL_APP_ARGUMENT = b"approve_proposal"
CANCEL_PROPOSAL_APP_ARGUMENT = b"cancel_proposal"
EXECUTE_PROPOSAL_APP_ARGUMENT = b"execute_proposal"
DISABLE_APPROVAL_REQUIREMENT_APP_ARGUMENT = b"disable_approval_requirement"
SET_PROPOSAL_THRESHOLD_APP_ARGUMENT = b"set_proposal_threshold"
SET_PROPOSAL_THRESHOLD_NUMERATOR_APP_ARGUMENT = b"set_proposal_threshold_numerator"
SET_QUORUM_THRESHOLD_APP_ARGUMENT = b"set_quorum_threshold"

PROPOSAL_STATE_WAITING_FOR_APPROVAL = 0
PROPOSAL_STATE_CANCELLED = 1
PROPOSAL_STATE_PENDING = 2
PROPOSAL_STATE_ACTIVE = 3
PROPOSAL_STATE_DEFEATED = 4
PROPOSAL_STATE_SUCCEEDED = 5
PROPOSAL_STATE_EXECUTED = 6

# Executors app arguments
VALIDATE_TRANSACTION_APP_ARGUMENT = b"validate_transaction"
VALIDATE_GROUP_APP_ARGUMENT = b"validate_group"
SET_FEE_SETTER_APP_ARGUMENT = b"set_fee_setter"
SET_FEE_MANAGER_APP_ARGUMENT = b"set_fee_manager"
SET_FEE_COLLECTOR_APP_ARGUMENT = b"set_fee_collector"
SET_FEE_FOR_POOL_APP_ARGUMENT = b"set_fee_for_pool"
SEND_APP_ARGUMENT = b"send"
ASSET_OPTIN_APP_ARGUMENT = b"asset_optin"

# Executors hash prefixes
VALIDATE_TRANSACTION_HASH_PREFIX = b"vt"
VALIDATE_GROUP_HASH_PREFIX = b"vg"
SET_FEE_SETTER_HASH_PREFIX = b"fs"
SET_FEE_MANAGER_HASH_PREFIX = b"fm"
SET_FEE_COLLECTOR_HASH_PREFIX = b"fc"
SET_FEE_FOR_POOL_HASH_PREFIX = b"sf"
SEND_HASH_PREFIX = b"sn"

EXECUTION_HASH_SIZE = 2 + 32
CREATE_PROPOSAL_DEFAULT_EXECUTION_HASH_ARGUMENT = b"\x00" * EXECUTION_HASH_SIZE
