BOOTSTRAP_APP_ARGUMENT = "Ym9vdHN0cmFw"
BURN_APP_ARGUMENT = "YnVybg=="
MINT_APP_ARGUMENT = "bWludA=="
REDEEM_APP_ARGUMENT = "cmVkZWVt"
SWAP_APP_ARGUMENT = "c3dhcA=="

TESTNET_VALIDATOR_APP_ID = 21580889
MAINNET_VALIDATOR_APP_ID = None
