from tinyman.constants import MINIMUM_BALANCE_REQUIREMENT_PER_BOX, MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE
from tinyman.governance.constants import WEEK

MIN_LOCK_TIME = 4 * WEEK                # 4 WEEK
MAX_LOCK_TIME = 4 * 52 * WEEK           # 364 * 4 Days
MIN_LOCK_AMOUNT = 10_000_000            # 10 TINY
MIN_LOCK_AMOUNT_INCREMENT = 10_000_000  # 10 TINY
TWO_TO_THE_64 = 2 ** 64                 # Scaling factor
# TWO_TO_THE_64 = "\x01\x00\x00\x00\x00\x00\x00\x00\x00"

# Global states
TOTAL_LOCKED_AMOUNT_KEY = b'total_locked_amount'
TOTAL_POWER_COUNT_KEY = b'total_power_count'
LAST_TOTAL_POWER_TIMESTAMP_KEY = b'last_total_power_timestamp'

# Boxes
TOTAL_POWERS = b'tp'
SLOPE_CHANGES = b'sc'

ACCOUNT_STATE_BOX_SIZE = 32
SLOPE_CHANGE_BOX_SIZE = 16

ACCOUNT_POWER_SIZE = 48
ACCOUNT_POWER_BOX_SIZE = 1008
ACCOUNT_POWER_BOX_ARRAY_LEN = 21

TOTAL_POWER_SIZE = 48
TOTAL_POWER_BOX_SIZE = 1008
TOTAL_POWER_BOX_ARRAY_LEN = 21

# 100_000 Default
# 100_000 Opt-in
# Box
# https://developer.algorand.org/docs/get-details/dapps/smart-contracts/apps/?from_query=box#minimum-balance-requirement-for-boxes
# 2500 + 400 * (len(n)+s)
# 2_500 Box
# 407_200 = 400 * (10 + 1008)
VAULT_APP_MINIMUM_BALANCE_REQUIREMENT = 609_700


ACCOUNT_STATE_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (32 + ACCOUNT_STATE_BOX_SIZE)
SLOPE_CHANGE_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (10 + SLOPE_CHANGE_BOX_SIZE)
ACCOUNT_POWER_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (40 + ACCOUNT_POWER_BOX_SIZE)
TOTAL_POWER_BOX_COST = MINIMUM_BALANCE_REQUIREMENT_PER_BOX + MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE * (10 + TOTAL_POWER_BOX_SIZE)

INIT_APP_ARGUMENT = b"init"
CREATE_LOCK_APP_ARGUMENT = b"create_lock"
CREATE_CHECKPOINTS_APP_ARGUMENT = b"create_checkpoints"
INCREASE_LOCK_AMOUNT_APP_ARGUMENT = b"increase_lock_amount"
EXTEND_LOCK_END_TIME_APP_ARGUMENT = b"extend_lock_end_time"
WITHDRAW_APP_ARGUMENT = b"withdraw"
GET_TINY_POWER_OF_APP_ARGUMENT = b"get_tiny_power_of"
GET_TINY_POWER_OF_AT_APP_ARGUMENT = b"get_tiny_power_of_at"
GET_TOTAL_TINY_POWER_APP_ARGUMENT = b"get_total_tiny_power"
GET_TOTAL_TINY_POWER_AT_APP_ARGUMENT = b"get_total_tiny_power_at"
GET_TOTAL_CUMULATIVE_POWER_AT_APP_ARGUMENT = b"get_total_cumulative_power_at"
GET_CUMULATIVE_POWER_OF_AT_APP_ARGUMENT = b"get_cumulative_power_of_at"
GET_ACCOUNT_CUMULATIVE_POWER_DELTA_APP_PREFIX = b"get_account_cumulative_power_delta"
GET_TOTAL_CUMULATIVE_POWER_DELTA_APP_PREFIX = b"get_total_cumulative_power_delta"
DELETE_ACCOUNT_POWER_BOXES_APP_ARGUMENT = b"delete_account_power_boxes"
DELETE_ACCOUNT_STATE_APP_ARGUMENT = b"delete_account_state"
